# Generated by Django 3.2.6 on 2021-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без заголовка', max_length=50, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, max_length=50, null=True, verbose_name='Аннотация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Новостная запись',
                'verbose_name_plural': 'Новостные записи',
            },
        ),
    ]
