# Generated by Django 3.2.6 on 2021-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=50, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.RemoveField(
            model_name='confirmcode',
            name='phone',
        ),
        migrations.AddField(
            model_name='confirmcode',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
