# Generated by Django 3.2.6 on 2021-08-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0003_auto_20210824_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmcode',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.user'),
        ),
    ]
