# Generated by Django 3.2.6 on 2021-08-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0004_alter_confirmcode_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmcode',
            old_name='username',
            new_name='user',
        ),
    ]
