# Generated by Django 3.2.6 on 2021-08-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Аннотация'),
        ),
    ]
