# Generated by Django 3.2.6 on 2021-08-31 15:15

from django.db import migrations, models
import django.db.models.deletion
import tlc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0008_about_attachmentphoto_chat_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='название товара')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('top', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'Категория продуктов',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents', validators=[tlc.validators.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='ProductResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='products_res_before', verbose_name='Фото до')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='products_res_after', verbose_name='Фото после')),
                ('text', models.TextField(blank=True, null=True, verbose_name='описание отзыва')),
                ('links', models.JSONField(default={})),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.product')),
            ],
            options={
                'verbose_name': 'Результат по продукту',
                'verbose_name_plural': 'Результаты по продукту',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.productcategory'),
        ),
    ]
