# Generated by Django 3.2.6 on 2021-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0009_auto_20210831_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresults',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
