# Generated by Django 3.2.6 on 2021-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0010_alter_productresults_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='top',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
