# Generated by Django 3.2.6 on 2021-08-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0011_alter_product_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresults',
            name='links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
