# Generated by Django 3.2.6 on 2021-09-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0014_auto_20210901_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
